# Generated by Django 3.0 on 2020-02-23 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dname', models.CharField(max_length=20)),
                ('dcode', models.IntegerField(primary_key=True, serialize=False)),
                ('number_of_employees', models.IntegerField()),
                ('budget', models.IntegerField()),
                ('last_inspection_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('ename', models.CharField(max_length=20)),
                ('ecode', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_date', models.DateTimeField()),
                ('salary', models.IntegerField()),
                ('last_inspection_date', models.DateTimeField()),
                ('inspected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Belview_Management.Employee')),
                ('works_in', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Belview_Management.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=20)),
                ('max_capacity', models.IntegerField()),
                ('in_charge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Belview_Management.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='in_charge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Belview_Management.Employee'),
        ),
        migrations.AddField(
            model_name='department',
            name='located_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Belview_Management.Location'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('occupation_status', models.CharField(max_length=20)),
                ('number_of_occupants', models.IntegerField()),
                ('room_type', models.CharField(max_length=20)),
                ('cost_per_day_peak', models.IntegerField()),
                ('cost_per_day_non_peak', models.IntegerField()),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Belview_Management.Location')),
            ],
            options={
                'unique_together': {('room_number', 'location')},
            },
        ),
    ]
